NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmarks/mbv2_custom_cifar100_224_e100_sgd'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 5
  EVAL_EPOCH: 5
  RESUME: False
  USE_TENSORBOARD: True
DATASET:
  NAME: 'CIFAR100'
  DATA_DIR: './data/cifar'
TRANSFORM:
  MEAN: (0.45, 0.45, 0.45)
  STD: (0.225, 0.225, 0.225)
  TRAIN:
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TRAIN_CROP_SIZE: 224
  TEST:
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TEST_CROP_SIZE: 224
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  CONV:
    TYPE: 'Conv2d'
  NORM:
    TYPE: 'BatchNorm2d'
    SYNC_BN: False
    FIX_BN: False
    PARTIAL_BN: False
  ACT:
    TYPE: 'ReLU6'
  COMPRESSION:
    WIDTH_MULTIPLIER: 1.0
    ROUND_NEAREST: 8
  BACKBONE:
    IN_PLANES: 3
    BASE_PLANES: 32
    FEATURE_DIMS: 1280
  HEAD:
    DROPOUT: 0.2
    NUM_CLASSES: 100
  RECOGNIZER:
    TYPE: 'MobileNetV2'
    NAME: 'CustomMobileNetV2'
    PRELOADED: ""
    PRETRAINED: ""
    PRETRAINED_NUM_CLASSES: 1000
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 0.0125
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 40, 70 ]
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0