NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmarks/mnasnet_b1_1_3_torchvision_cifar100_224_e100'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 5
  EVAL_EPOCH: 5
  RESUME: False
  USE_TENSORBOARD: True
DATASET:
  NAME: 'CIFAR100'
  DATA_DIR: './data/cifar'
TRANSFORM:
  MEAN: (0.45, 0.45, 0.45)
  STD: (0.225, 0.225, 0.225)
  TRAIN:
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TRAIN_CROP_SIZE: 224
  TEST:
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TEST_CROP_SIZE: 224
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  NORM:
    SYNC_BN: False
    FIX_BN: False
    PARTIAL_BN: False
  COMPRESSION:
    WIDTH_MULTIPLIER: 1.3
  HEAD:
    NUM_CLASSES: 100
  RECOGNIZER:
    TYPE: 'MNASNet'
    NAME: 'TorchvisionMNASNet'
    PRELOADED: ""
    TORCHVISION_PRETRAINED: False
    PRETRAINED_NUM_CLASSES: 1000
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'RMSProp'
  LR: 3e-4
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 40, 70 ]
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0