NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/r50_precise_bn_custom_cifar100_224_ga10'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEPS: 10
  MAX_EPOCH: 200
  SAVE_EPOCH: 5
  EVAL_EPOCH: 5
  RESUME: False
  USE_TENSORBOARD: True
DATASET:
  NAME: 'CIFAR100'
  DATA_DIR: './data/cifar'
TRANSFORM:
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  TRAIN:
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TRAIN_CROP_SIZE: 224
  TEST:
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TEST_CROP_SIZE: 224
DATALOADER:
  TRAIN_BATCH_SIZE: 80
  TEST_BATCH_SIZE: 80
  NUM_WORKERS: 8
MODEL:
  NAME: 'ResNet'
  PRETRAINED: ''
  TORCHVISION_PRETRAINED: False
  NORM:
    TYPE: 'BatchNorm2d'
    SYNC_BN: False
    FIX_BN: False
    PARTIAL_BN: False
    PRECISE_BN: True
  BACKBONE:
    ARCH: 'resnet50'
  HEAD:
    FEATURE_DIMS: 2048
    NUM_CLASSES: 100
  RECOGNIZER:
    NAME: 'ResNet_Custom'
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 1e-3
  WEIGHT_DECAY: 1e-5
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 100, 150, 175 ]
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0